// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options4.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FourthFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwHgPKG1WysG40MuWmQs0pqP8MQHahTg',
    appId: '1:434464302156:web:72aafa5247f0664011c0e9',
    messagingSenderId: '434464302156',
    projectId: 'skv-school-5e60f',
    authDomain: 'skv-school-5e60f.firebaseapp.com',
    storageBucket: 'skv-school-5e60f.appspot.com',
    measurementId: 'G-71QTWXY4C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRyrNzagAOnYtBImV6vA1blsGDFsh5uyI',
    appId: '1:434464302156:android:10463d76bb5d0f2711c0e9',
    messagingSenderId: '434464302156',
    projectId: 'skv-school-5e60f',
    storageBucket: 'skv-school-5e60f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0BvBjtzxHyq-or_cpGD48SaLZs7yMeI',
    appId: '1:434464302156:ios:031a9eabb384b55011c0e9',
    messagingSenderId: '434464302156',
    projectId: 'skv-school-5e60f',
    storageBucket: 'skv-school-5e60f.appspot.com',
    iosBundleId: 'com.example.vidhaanSchoolApp',
  );
}
