// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options3.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ThirdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMIhxVxa2ZSEI0DBJHgv4hKSigR8-Hgc',
    appId: '1:256400049959:web:0ea069d361ff73ebaf4b02',
    messagingSenderId: '256400049959',
    projectId: 'shreesaividhaan-672cd',
    authDomain: 'shreesaividhaan-672cd.firebaseapp.com',
    storageBucket: 'shreesaividhaan-672cd.appspot.com',
    measurementId: 'G-YFE6ND7RZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTmwKQ1vQHjmhqP8y3J5FtLYc_6Bht1M',
    appId: '1:256400049959:android:11595d49fb4477a9af4b02',
    messagingSenderId: '256400049959',
    projectId: 'shreesaividhaan-672cd',
    storageBucket: 'shreesaividhaan-672cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0tl5KHi0c_kU3i7IrjzhzeA7KsDw5b4',
    appId: '1:256400049959:ios:c917b631db6519d6af4b02',
    messagingSenderId: '256400049959',
    projectId: 'shreesaividhaan-672cd',
    storageBucket: 'shreesaividhaan-672cd.appspot.com',
    iosBundleId: 'com.example.vidhaanSchoolApp',
  );
}
