// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options5.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FifthFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-TW0DIYl9loTda-zHQO0aFRwpZAALUI',
    appId: '1:1052400533176:web:76e8dccd2747f77f987e4d',
    messagingSenderId: '1052400533176',
    projectId: 'adithya-vidhyashram',
    authDomain: 'adithya-vidhyashram.firebaseapp.com',
    storageBucket: 'adithya-vidhyashram.appspot.com',
    measurementId: 'G-38HX23ZX0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cr6fQhsH74eoufUQpXZ-_IgGjyKMZLg',
    appId: '1:1052400533176:android:05597ede8cf00ccf987e4d',
    messagingSenderId: '1052400533176',
    projectId: 'adithya-vidhyashram',
    storageBucket: 'adithya-vidhyashram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHfBI2dXhZaw_0f70XIOquVq9pWJpTb8',
    appId: '1:1052400533176:ios:61cbe0a692d5d0e4987e4d',
    messagingSenderId: '1052400533176',
    projectId: 'adithya-vidhyashram',
    storageBucket: 'adithya-vidhyashram.appspot.com',
    iosBundleId: 'com.example.vidhaanSchoolApp',
  );
}
