// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAca1G4Iz-UmDsNeHjkfcegAP7z2LGOUKg',
    appId: '1:453216660661:web:b21015a7f2069aae2fe2fc',
    messagingSenderId: '453216660661',
    projectId: 'vidhaan-live',
    authDomain: 'vidhaan-live.firebaseapp.com',
    storageBucket: 'vidhaan-live.appspot.com',
    measurementId: 'G-5L8V6NYX8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wwjZ7skyUd4vsWe7LFCBYjRlCn2eMnA',
    appId: '1:453216660661:android:a4f1faeadb7f8ba32fe2fc',
    messagingSenderId: '453216660661',
    projectId: 'vidhaan-live',
    storageBucket: 'vidhaan-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPLGvxZ-jrwHVqHy1sdTVe1tSJF7VyvY',
    appId: '1:453216660661:ios:0f63b20534dde6422fe2fc',
    messagingSenderId: '453216660661',
    projectId: 'vidhaan-live',
    storageBucket: 'vidhaan-live.appspot.com',
    iosBundleId: 'com.example.vidhaanSchoolApp',
  );
}
